#!/usr/bin/env bash

# This script runs, demonizes, keeps alive and watches all relevant services (e.g. the API) in the project.

# scripts directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd "$SCRIPTDIR"

# Same thing can be done with forever
# forever stop api.js
# forever start -w -t api.js
# forever stop data-update-server.js
# forever start -w -t data-update-server.js


pm2 start game.js --watch --name "ww-game"
# pm2 restart data-update-server.js --watch --name "semweb-data-update-server"