#!/usr/bin/env bash

# This script stops all running services (e.g. the API) in the project.

# scripts directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd "$SCRIPTDIR"

# Same thing can be done with forever
# forever stop api.js
# forever stop data-update-server.js

pm2 stop ww-game --watch
# pm2 stop tmcdemo-data-update-server --watch